# Generated by Django 2.1.5 on 2019-06-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Emp',
        ),
    ]
